# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 10:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_]+$'), b'Allowed characters: letters, numbers and underscores.', b'invalid')])),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVclTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_]+$'), b'Allowed characters: letters, numbers and underscores.', b'invalid')])),
                ('content', models.TextField()),
                ('version', models.CharField(choices=[(b'3.0', b'Vcl 3.0'), (b'4.0', b'Vcl 4.0')], default=b'4.0', max_length=3)),
                ('comment', models.CharField(max_length=64)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical vcl template',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVclTemplateBlock',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tag', models.CharField(choices=[(b'VCL', b'VCL'), (b'HEADERS', b'VCL/HEADERS'), (b'ACL', b'VCL/ACL'), (b'BACKENDS', b'VCL/BACKENDS'), (b'DIRECTORS', b'VCL/DIRECTORS'), (b'RECV', b'VCL/RECEIVE'), (b'ROUTER', b'VCL/RECEIVE/ROUTER'), (b'PROPER_PROTOCOL_REDIRECT', b'RECEIVE/PROPER_PROTOCOL_REDIRECT'), (b'OTHER_FUNCTIONS', b'VCL/OTHER_FUNCTIONS')], max_length=100)),
                ('content', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical vcl template block',
            },
        ),
        migrations.CreateModel(
            name='LogicalCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_]+$'), b'Allowed characters: letters, numbers and underscores.', b'invalid')])),
                ('reload_timestamp', models.DateTimeField(default=datetime.datetime(2016, 12, 18, 10, 58, 49, 151094, tzinfo=utc))),
                ('error_timestamp', models.DateTimeField(default=datetime.datetime(2016, 12, 18, 10, 58, 49, 151131, tzinfo=utc))),
                ('last_error_info', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarnishServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol=b'IPv4')),
                ('hostname', models.CharField(max_length=50)),
                ('cluster_weight', models.PositiveIntegerField(default=b'1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('port', models.PositiveIntegerField(default=b'6082', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('secret', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[(b'active', b'Active'), (b'maintenance', b'Maintenance'), (b'disabled', b'Disabled')], default=b'disabled', max_length=15)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cluster.LogicalCluster')),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cluster.Dc')),
            ],
        ),
        migrations.CreateModel(
            name='VclTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_]+$'), b'Allowed characters: letters, numbers and underscores.', b'invalid')])),
                ('content', models.TextField()),
                ('version', models.CharField(choices=[(b'3.0', b'Vcl 3.0'), (b'4.0', b'Vcl 4.0')], default=b'4.0', max_length=3)),
                ('comment', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VclTemplateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[(b'VCL', b'VCL'), (b'HEADERS', b'VCL/HEADERS'), (b'ACL', b'VCL/ACL'), (b'BACKENDS', b'VCL/BACKENDS'), (b'DIRECTORS', b'VCL/DIRECTORS'), (b'RECV', b'VCL/RECEIVE'), (b'ROUTER', b'VCL/RECEIVE/ROUTER'), (b'PROPER_PROTOCOL_REDIRECT', b'RECEIVE/PROPER_PROTOCOL_REDIRECT'), (b'OTHER_FUNCTIONS', b'VCL/OTHER_FUNCTIONS')], max_length=100)),
                ('content', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cluster.VclTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='varnishserver',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cluster.VclTemplate'),
        ),
        migrations.AddField(
            model_name='historicalvcltemplateblock',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cluster.VclTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='vcltemplateblock',
            unique_together=set([('tag', 'template')]),
        ),
        migrations.AlterUniqueTogether(
            name='varnishserver',
            unique_together=set([('ip', 'port')]),
        ),
    ]
